version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      # - DATABASE_URL=postgres://expense:postgres@db:5432/expense_tracker_dev
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=expense
      - POSTGRES_PASSWORD=wZSP%Opq8dmEm9@E
      - POSTGRES_DB=expense_tracker_dev
    ports:
      - "5432:5432"
    volumes:
      - ./backend/src/database/sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
